services:

  traefik:
    image: "traefik:v3.2"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--accesslog=true"
      - "--entryPoints.web.address=:80"
      # TLS
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt_volume:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
     - tpm_network

  teampasswordmanager:
    image: teampasswordmanager/teampasswordmanager:latest
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - tpm_volume:/var/www/html
    networks:
     - tpm_network
    environment:
      - TPM_SERVER_TIMEZONE=Etc/UTC
      - TPM_PHP_TIMEZONE=Etc/UTC
      - TPM_ENCRYPT_DB_CONFIG=0
      - TPM_CONFIG_HOSTNAME=mysql
      - TPM_CONFIG_PORT=3306
      - TPM_CONFIG_USERNAME=tpm_user
      - TPM_CONFIG_PASSWORD=tpm_password
      - TPM_CONFIG_DATABASE=tpm_database
      - TPM_UPGRADE=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teampasswordmanager.rule=Host(`teampasswordmanager.localhost`)"
      - "traefik.http.routers.teampasswordmanager.entrypoints=websecure"
      - "traefik.http.routers.teampasswordmanager.tls.certresolver=myresolver"

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    volumes:
      - tpm_mysqldata:/var/lib/mysql
    networks:
     - tpm_network
    environment:
      - MYSQL_USER=tpm_user
      - MYSQL_PASSWORD=tpm_password
      - MYSQL_DATABASE=tpm_database
      - MYSQL_ROOT_PASSWORD=password5.7

networks:
  tpm_network:
    driver: "bridge"

volumes:
  tpm_mysqldata:
    driver: "local"
  tpm_volume:
    driver: "local"
  letsencrypt_volume:
    driver: "local"
