// Code generated by "stringer -type=ExpireStatus"; DO NOT EDIT.

package tpm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotExpired-0]
	_ = x[ExpiresToday-1]
	_ = x[Expired-2]
	_ = x[ExpiresSoon-3]
}

const _ExpireStatus_name = "NotExpiredExpiresTodayExpiredExpiresSoon"

var _ExpireStatus_index = [...]uint8{0, 10, 22, 29, 40}

func (i ExpireStatus) String() string {
	if i < 0 || i >= ExpireStatus(len(_ExpireStatus_index)-1) {
		return "ExpireStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpireStatus_name[_ExpireStatus_index[i]:_ExpireStatus_index[i+1]]
}
