// Code generated by "stringer -type=LockingType"; DO NOT EDIT.

package tpm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotLocked-0]
	_ = x[RequiresReasonToUnlock-1]
	_ = x[RequiresPermissionToUnlock-2]
}

const _LockingType_name = "NotLockedRequiresReasonToUnlockRequiresPermissionToUnlock"

var _LockingType_index = [...]uint8{0, 9, 31, 57}

func (i LockingType) String() string {
	if i < 0 || i >= LockingType(len(_LockingType_index)-1) {
		return "LockingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LockingType_name[_LockingType_index[i]:_LockingType_index[i+1]]
}
